### ISSUE TITLE
Options order

### ISSUE THREAD

**Issue by jmtellez** [jmtellez/CLI-mate#11]
Work on the order on how the location and units are passed. Order should not matter:

```
$ cli-mate Dallas --u=m
$ cli-mate --u=m Dallas
```
 both should return the same output:

```
✔ Dallas, Texas, United States
Partly cloudy. It is currently 23°C, it feels like 24°C.
```

**Comment by sampjr** [comment]
The following command returns actual data haha!
>cli-mate --u=m Dallas

https://api.mapbox.com/geocoding/v5/mapbox.places/**--u%3Dm**.json?access_token=<token>
√ U-M Soccer Complex, 2250 S. State St., Ann Arbor, Michigan 48103, United States

**Comment by jmtellez** [comment]
Right it's taking the first argument as the location.

**Comment by jsilvaigor** [comment]
We can improve argument parsing using a library like [argparse](https://www.npmjs.com/package/argparse) and it will also auto-generate the help menu based on the configs. I'll fork the repo and open a PR making this changes.

**Comment by vzsky** [comment]
Sorry @jsilvaigor. I didn't see your comment and I managed to solve this issue.
Please refer to #13

**Comment by jsilvaigor** [comment]
No problem @vzsky
