### ISSUE TITLE
setTimeout() wraps all network calls? 

### ISSUE THREAD

**Issue by r-i-c-h** [jmtellez/CLI-mate#24]
Why do all of the network calls happen after a 1second setTimeout()? 

If it's a question of the state of the request connection, according to the documentation on https://github.com/postmanlabs/postman-request#requestoptions-callback - request's options object takes a `timeout:` value which should cover this. 

Otherwise, I'd suggest perhaps working with returning a Promise or an Async/Await style for http requests?

**Comment by jmtellez** [comment]
`setTimeout()` is there to allow the user to see the ora spinner, feel free to work on change and open a PR
