### ISSUE TITLE
Units Flag

### ISSUE THREAD

**Issue by jmtellez** [jmtellez/CLI-mate#4]
Weather data is returned in Fahrenheit. 
Add flag to pass desired units (check WeatherStack API for units)

**Comment by MKPATH2015** [comment]
Can I work on this?

**Comment by CarlyRaeJepsenStan** [comment]
Should this flag consume input, or just be `-C` or `-F` and `-K`?

**Comment by jmtellez** [comment]
Flag should consume inputs. WeatherStack API has a section on units be default is Fahrenheit.

It could be something like `cli-mate <location> -u=m`
