### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by CarlyRaeJepsenStan** [jmtellez/CLI-mate#6]
```
➜  ~ cli-mate mcallen
⠸ Getting geocodes/usr/local/lib/node_modules/@jmt3559/cli-mate/utils/geocode.js:14
      } else if (body.features.length === 0) {
                               ^

TypeError: Cannot read property 'length' of undefined

```
Possible REST API parse error - I'll try to fix this, but put it out here so others can see it.

**Comment by jmtellez** [comment]
Its on the README.md

**Comment by CarlyRaeJepsenStan** [comment]
Anyway to expose the API keys?  I just got a mapbox API key, but its still throwing the same error.

**Comment by jmtellez** [comment]
Make sure you are naming your environment variables exactly as the README says. 
`process.env` property returns an object containing the user environment, no need for `.env` file

**Comment by CarlyRaeJepsenStan** [comment]
Turns out the API keys are contained in `~/.zprofile`.
I'm re-opening this issue because cli-mate is unfortunately parsing the response JSON wrong - I manually queried the URL with postman and it returned this:

```
{
    "type": "FeatureCollection",
    "query": [
        "mcallen"
    ],
    "features": [
        {
            "id": "place.9211585200717980",
            "type": "Feature",
            "place_type": [
...
```

I think I should be able to get the keys with `[features]` instead of `.features` - my fork [here](github.com/CarlyRaeJepsenStan/CLI-mate)

**Comment by jmtellez** [comment]
Look at the response from your snippet above:

```
{
    "type": "FeatureCollection",
    "query": [
        "mcallen"
    ],
    "features": [
        {
            "id": "place.9211585200717980",
            "type": "Feature",
            "place_type": [
...
```

`features` is a JSON property, so dot notation is correct. Arrays can be values of an object property like `features` that is why your output is showing 5.
we are using the first value in the array as it the most relevant result.
